#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

platform:
  - x64

environment:
  global:
    BINTRAY_API:
      secure: a9n4jf90wlFCdaYa6fOmYxsF97ur2dnK8Ys3gn5R90JBzTDq6cD2GlEwmmts75mq
    BINTRAY_USERNAME: tkralphs
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      ARCH: win32-msvc14-md
      HOST_ARCH_ARG: --enable-msvc=MD
      ADD_PATH: /mingw64/bin
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: win32-msvc15-md
      HOST_ARCH_ARG: --enable-msvc=MD
      ADD_PATH: /mingw64/bin
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: win32-msvc16-md
      HOST_ARCH_ARG: --enable-msvc=MD
      ADD_PATH: /mingw64/bin
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: x86_64-w64-mingw32
      HOST_ARCH_ARG: --host=x86_64-w64-mingw32
      ADD_PATH: /mingw64/bin
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: i686-w64-mingw32
      HOST_ARCH_ARG: --host=i686-w64-mingw32
      ADD_PATH: /mingw32/bin

install:
  - for /f "delims=" %%i in ('C:\msys64\usr\bin\bash -lc "if [ $APPVEYOR_REPO_BRANCH = 'master' ]; then echo 'master'; else echo $APPVEYOR_REPO_BRANCH | cut -d "/" -f 2; fi"') do set VERSION=%%i
  - IF %ARCH%==win32-msvc14 (CALL C:\"Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat")
  - IF %ARCH%==win32-msvc15 (CALL C:\"Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64)
  - IF %ARCH%==win32-msvc16 (CALL C:\"Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64)
  - IF %ARCH%==x86_64-w64-mingw32 (CALL C:\msys64\usr\bin\bash -lc "pacman -S mingw-w64-x86_64-lapack mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-readline mingw-w64-x86_64-suitesparse  mingw-w64-x86_64-metis --noconfirm")
  - IF %ARCH%==i686-w64-mingw32 (CALL C:\msys64\usr\bin\bash -lc "pacman -S mingw-w64-i686-lapack mingw-w64-i686-winpthreads-git mingw-w64-i686-readline mingw-w64-i686-suitesparse  mingw-w64-i686-metis --noconfirm")  
  - C:\msys64\usr\bin\bash -lc ""

build_script:
  - C:\msys64\usr\bin\bash -lc "cd C:\projects; ln -s %APPVEYOR_PROJECT_SLUG% %APPVEYOR_PROJECT_NAME%; wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew"
  - C:\msys64\usr\bin\bash -lc "cd C:\projects; ./coinbrew fetch https://github.com/%APPVEYOR_REPO_NAME%:%APPVEYOR_REPO_BRANCH% --no-prompt --no-third-party --skip-update"
  - C:\msys64\usr\bin\bash -lc "cd C:\projects; export PATH=$ADD_PATH:$PATH; ./coinbrew build %APPVEYOR_PROJECT_NAME% --no-prompt --build=x86_64-w64-mingw32 $HOST_ARCH_ARG --verbosity 2 --tests main --enable-relocatable --no-third-party"

after_build:
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libblas.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libopenblas.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\liblapack.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libgfortran-5.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libgcc_s_seh-1.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libbz2-1.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libwinpthread-1.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libstdc++-6.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libquadmath-0.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libreadline8.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libtermcap-0.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\zlib1.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libcholmod.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libcolamd.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libccolamd.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libamd.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libcamd.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libmetis.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libgomp-1.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libsuitesparseconfig.dll C:\projects\dist\bin)
  - IF %ARCH%==x86_64-w64-mingw32 (cp C:\msys64\mingw64\bin\libmetis.dll C:\projects\dist\bin)

  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libblas.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\liblapack.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libgfortran-5.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libgcc_s_dw2-1.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libbz2-1.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libwinpthread-1.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libstdc++-6.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libquadmath-0.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libreadline8.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libtermcap-0.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\zlib1.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libcholmod.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libcolamd.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libccolamd.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libamd.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libcamd.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libmetis.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libgomp-1.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libsuitesparseconfig.dll C:\projects\dist\bin)
  - IF %ARCH%==i686-w64-mingw32 (cp C:\msys64\mingw32\bin\libmetis.dll C:\projects\dist\bin)
  - 7z a %APPVEYOR_PROJECT_NAME%-%VERSION%-%ARCH%.zip C:\projects\dist\bin
  - 7z a %APPVEYOR_PROJECT_NAME%-%VERSION%-%ARCH%.zip C:\projects\dist\include
  - 7z a %APPVEYOR_PROJECT_NAME%-%VERSION%-%ARCH%.zip C:\projects\dist\lib
  - 7z a %APPVEYOR_PROJECT_NAME%-%VERSION%-%ARCH%.zip C:\projects\dist\share
  - 7z a %APPVEYOR_PROJECT_NAME%-%VERSION%-%ARCH%.zip C:\projects\%APPVEYOR_PROJECT_NAME%\README.md
  - 7z a %APPVEYOR_PROJECT_NAME%-%VERSION%-%ARCH%.zip C:\projects\%APPVEYOR_PROJECT_NAME%\LICENSE
  - 7z a %APPVEYOR_PROJECT_NAME%-%VERSION%-%ARCH%.zip C:\projects\%APPVEYOR_PROJECT_NAME%\INSTALL
  - 7z a %APPVEYOR_PROJECT_NAME%-%VERSION%-%ARCH%.zip C:\projects\%APPVEYOR_PROJECT_NAME%\%APPVEYOR_PROJECT_NAME%\AUTHORS
  - curl -T %APPVEYOR_PROJECT_NAME%-%VERSION%-%ARCH%.zip -utkralphs:%BINTRAY_API% -H "X-Bintray-Publish:1" -H "X-Bintray-Override:1" https://api.bintray.com/content/coin-or/download/%APPVEYOR_PROJECT_NAME%/%VERSION%/%APPVEYOR_PROJECT_NAME%-%VERSION%-%ARCH%.zip

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
