Description:
  Slug: Dip
  ShortName: Dip
  LongName:
  ShortDescription: A framework for implementing a variety of decomposition-based branch-and-bound algorithms for solving mixed-integer linear programs.
  LongDescription: |2
    DIP (Decomposition in Integer Programming) is a framework for
    implementing a wide variety of decomposition-based algorithms
    for solving integer programs.
  Manager: Ted Ralphs, ted at lehigh dot edu 
  Homepage: https://github.com/coin-or/Dip
  License: Eclipse Public License 2.0
  LicenseURL: http://www.opensource.org/licenses/eclipse-2.0
  Zenodo: 23778922
  IncludedIn:
    Package: Dip
  Language:
    - C++
  Categories: 
    - Optimization deterministic linear discrete
  PaperCite: http://dx.doi.org/10.1007/s10107-005-0606-3
Dependencies:
  - Description: Sample data files
    URL: https://github.com/coin-or-tools/Data-Sample
    Version: 1.2
    Required: Required
  - Description: COIN-OR Utilities
    URL: https://github.com/coin-or/CoinUtils
    Version: 2.11
    Required: Required
  - Description: Open Solver Interface
    URL: https://github.com/coin-or/Osi
    Version: 0.108
    Required: Required
  - Description: COIN-OR LP Solver
    URL: https://github.com/coin-or/Clp
    Version: 1.17
    Required: Required
  - Description: The Cut Generator Library
    URL: https://github.com/coin-or/Cgl
    Version: 0.60
    Required: Required
  - Description: COIN-OR Branch-and-cut
    URL: https://github.com/coin-or/Cbc
    Version: 2.10
    Required: Required
  - Description: Abstract Library for Parallel Search.
    URL: https://github.com/coin-or/CHiPPS-ALPS
    Version: 1.5
    Required: Required
  - Description: Abstract Library for Parallel Search.
    URL: https://github.com/coin-or/SYMPHONY
    Version: 5.6
    Required: Required
  - Description: Basic Linear Algebra Subroutines (BLAS)
    URL: http://www.netlib.org/blas
    Required: Recommended
  - Description: Linear Algebra Package (LAPACK)
    URL: http://www.netlib.org/lapack
    Required: Recommended

DevelopmentStatus: 
  activityStatus: Active
  maturityLevel: 5
  testedPlatforms: 
  - operatingSystem: Linux
    compiler: gcc
  - operatingSystem: Mac OS X
    compiler:
    - gcc
    - clang
  - operatingSystem: Microsoft Windows
    compiler: cl
  - operatingSystem: Microsoft Windows with MSys2
    compiler:
    - gcc
    - cl
    - icl
  - operatingSystem: Microsoft Windows Subsystem for Linux
    compiler:
    - gcc
    - cl
    - icl
